spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: ${DB_USER:myuser}
    password: ${DB_PASSWORD:secret}
  flyway:
    url: jdbc:postgresql://localhost:5432/mydatabase
    user: ${DB_USER:myuser}
    password: ${DB_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true