spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase?options=-c%20timezone=UTC
    username: myuser
    password: secret
  flyway:
    url: jdbc:postgresql://localhost:5432/mydatabase?options=-c%20timezone=UTC
    user: myuser
    password: secret